chs.api-key=${CHS_API_KEY}
account.url=${ACCOUNT_LOCAL_URL}
spring.thymeleaf.render-hidden-markers-before-checkboxes=true
server.servlet.session.cookie.secure=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
welshLanguage.enabled=false
management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/auth-code-requests
management.endpoints.web.path-mapping.health=/healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true

# Properties required by common-web-java
commonweb.cdn-url=//${CDN_HOST}
commonweb.chs-url=${CHS_URL}
commonweb.piwik-url=${PIWIK_URL}
commonweb.piwik-site-id=${PIWIK_SITE_ID}
commonweb.contactUsUrl=${CONTACT_US_URL}
commonweb.developer-url=${DEVELOPER_URL}